import { Noticia, NoticiaPreview, NoticiaTrending, Resource } from "./types";

const noticias: Noticia[] = [
  {
    slug: "new-rambo-attack-uses-ram-radio-signals.html",
    urlCapa: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi4EnB4iNTdy1F9L0G2ZgKV4zzkaU8cc7-eaTm-7nOzTFgThJCd8lQXG0MsTWDscRx4Vyvth3DUiTTe_yw_dD5_LiEjbgvjO_GxzHU7O9J0aPZ65LoJSjRstlB7rL4EBTB7pwHJajlFmFt80gLNODzTXsq8sgpU8k9cOiU6-IBwnFsP0lcHemXDbIa02sSD/s728-rw-e365/airgap.png",
    titulo: "New RAMBO Attack Uses RAM Radio Signals to Steal Data from Air-Gapped Networks",
    dataPublicacao: new Date(),
    tags: ["Vulnerability", " Hardware Security"],
    resumo: ` A novel side-channel attack has been found to leverage radio signals emanated by a device's random access memory (RAM) as a data exfiltration mechanism, posing a threat to air-gapped networks. The technique has been codenamed RAMBO by Dr. Mordechai Guri, the head of the Offensive Cyber Research Lab in the Department of Software and Information Systems Engineering at the Ben Gurion University of the Negev in Israel. "Using software-generated radio signals, malware can encode sensitive information such as files, images, keylogging, biometric information, and encryption keys," Dr. Guri said in a newly published research paper.`,
    autor: "Ravie Lakshmanan",
    paragrafos: [
      "A novel side-channel attack has been found to leverage radio signals emanated by a device's random access memory (RAM) as a data exfiltration mechanism, posing a threat to air-gapped networks.",
      "The technique has been codenamed <strong>RAMBO</strong> by Dr. Mordechai Guri, the head of the Offensive Cyber Research Lab in the Department of Software and Information Systems Engineering at the Ben Gurion University of the Negev in Israel.",
      `"Using software-generated radio signals, malware can encode sensitive information such as files, images, keylogging, biometric information, and encryption keys," Dr. Guri <a href="https://arxiv.org/abs/2409.02292" rel="noopener" target="_blank">said</a> in a newly published research paper.`,
      `"With software-defined radio (SDR) hardware, and a simple off-the-shelf antenna, an attacker can intercept transmitted raw radio signals from a distance. The signals can then be decoded and translated back into binary information."`,
      `Over the years, Dr. Guri has <a href="https://www.covertchannels.com" rel="noopener" target="_blank">concocted</a> various mechanisms to extract confidential data from offline networks by taking advantage of Serial ATA cables (<a href="https://thehackernews.com/2022/07/new-air-gap-attack-uses-sata-cable-as.html" rel="noopener" target="_blank">SATAn</a>), MEMS gyroscope (<a href="https://thehackernews.com/2022/08/new-air-gap-attack-uses-mems-gyroscope.html" rel="noopener" target="_blank">GAIROSCOPE</a>), LEDs on network interface cards (<a href="https://thehackernews.com/2022/08/air-gapped-devices-can-send-covert.html" rel="noopener" target="_blank">ETHERLED</a>), and dynamic power consumption (<a href="https://thehackernews.com/2022/12/covid-bit-new-covert-channel-to.html" rel="noopener" target="_blank">COVID-bit</a>).`,
      `Some of the other unconventional approaches devised by the researcher entail leaking data from air-gapped networks via covert acoustic signals generated by graphics processing unit (GPU) fans (<a href="https://link.springer.com/chapter/10.1007/978-3-031-22295-5_11" rel="noopener" target="_blank">GPU-FAN</a>), (ultra)sonic waves produced by built-in motherboard buzzers (<a href="https://www.computer.org/csdl/proceedings-article/pst/2023/10319985/1SjejUJaLgA" rel="noopener" target="_blank">EL-GRILLO</a>), and even printer display panels and status LEDs (<a href="https://link.springer.com/chapter/10.1007/978-3-031-37111-0_15" rel="noopener" target="_blank">PrinterLeak</a>).`,
      `<div className="video-container"><iframe allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen="" frameborder="0" height="315" referrerpolicy="strict-origin-when-cross-origin" src="https://www.youtube.com/embed/BLJcUXd2nyA?si=LudzN_EekwotSPGD" title="YouTube video player" width="560"></iframe></div>`,
      `Last year, Guri also demonstrated <a href="https://www.computer.org/csdl/proceedings-article/compsac/2023/269700a637/1PhCRSujeBa" rel="noopener" target="_blank">AirKeyLogger</a>, a hardwareless radio frequency keylogging attack that weaponizes radio emissions from a computer's power supply to exfiltrate real-time keystroke data to a remote attacker.`,
      `"To leak confidential data, the processor's working frequencies are manipulated to generate a pattern of electromagnetic emissions from the power unit modulated by keystrokes," Guri noted in the study. "The keystroke information can be received at distances of several meters away via an RF receiver or a smartphone with a simple antenna."`,
      `As always with attacks of this kind, it requires the air-gapped network to be first <a href="https://thehackernews.com/2023/10/tetrisphantom-cyber-espionage-via.html" rel="noopener" target="_blank">compromised</a> <a href="https://thehackernews.com/2023/10/sophisticated-mata-framework-strikes.html" rel="noopener" target="_blank">through</a> <a href="https://thehackernews.com/2024/07/french-authorities-launch-operation-to.html" rel="noopener" target="_blank">other means</a> – such as a rogue insider, poisoned USB drives, or a supply chain attack – thereby allowing the malware to trigger the covert data exfiltration channel.`,
      `RAMBO is no exception in that the malware is used to manipulate RAM such that it can generate radio signals at clock frequencies, which are then encoded using <a href="https://en.wikipedia.org/wiki/Manchester_code" rel="noopener" target="_blank">Manchester encoding</a> and transmitted so as to be received from a distance away.`,
      `The encoded data can include keystrokes, documents, and biometric information. An attacker on the other end can then leverage SDR to receive the electromagnetic signals, demodulate and decode the data, and retrieve the exfiltrated information.`,
      `"The malware utilizes electromagnetic emissions from the RAM to modulate the information and transmit it outward," Dr. Guri said. "A remote attacker with a radio receiver and antenna can receive the information, demodulate it, and decode it into its original binary or textual representation."`,
      `Found this article interesting? Follow us on <a href="https://twitter.com/thehackersnews" rel="noopener" target="_blank">Twitter </a> and <a href="https://www.linkedin.com/company/thehackernews/" rel="noopener" target="_blank">LinkedIn</a> to read more exclusive content we post.`,
    ]
  },
  {
    slug: "not-1",
    urlCapa:
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiKmMX999zXB84oRNczWEK4W8VodaujsXWikVA1avU_osbjwleTfC79P6nFmxp3rUPGQk3ZKNCc93KRO_m8cO5yTfCeksQxNdWJl5__OqjppwavG_7bYX0ZgAihKpCd3nJ5SApPf490exk3_j6suXuci9htjITCz2GYWVtZz6GZgsBwIOWMYERIQ_zvB9W7/s728-rw-e365/chinese-hacker.png",
    titulo: "macOS Version of HZ RAT Backdoor Targets Chinese Messaging App Users",
    dataPublicacao: new Date(),
    tags: ["Backdoor", "macOS"],
    resumo:
      "A new macOS version of the HZ RAT has been discovered in the wild, targeting users of the Chinese messaging app QQ. The backdoor is capable of exfiltrating files, capturing screenshots, and executing arbitrary commands on the infected machine.",
    autor: "John Doe",
    paragrafos: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec elit tincidunt interdum. Sed at turpis nec nunc ultricies mattis",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec elit tincidunt interdum. Sed at turpis nec nunc ultricies mattis"
    ]
  },
  {
    slug: "noticia-2",
    urlCapa:
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh_E4LUK0YF-ig9M9pBoT67TAwZ_EzcZ2sYtFmzhIow9hXpx5A16jE5zkc9aXH0Bd7BdyNYmTDzEs1NnMvog-KgTlDRJw4Tfn1LX-0HBXpixC_qm2Z_0-aInNUMr8BnPDGGltxHtwJ3vMuBkzC3OFDmfEp1MXs1QmUMhui-LaqDgWWfSJqJ1dNGQSgxo1cu/s728-rw-e365/sonic.jpg",
    titulo: "SonicWall Issues Critical Patch for Firewall Vulnerability Allowing Unauthorized Access",
    dataPublicacao: new Date(),
    tags: ["Firewall", "Vulnerability"],
    resumo:
      "SonicWall has released a critical security patch for a vulnerability affecting its Network Security Appliance (NSA) and Secure Mobile Access (SMA) products. The flaw, tracked as CVE-2021-20016, could allow attackers to gain unauthorized access to the firewall.",
    autor: "Frank Doe",
    paragrafos: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec elit tincidunt interdum. Sed at turpis nec nunc ultricies mattis",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec elit tincidunt interdum. Sed at turpis nec nunc ultricies mattis"
    ]
  },
  {
    slug: "noticia-3",
    urlCapa:
      "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjxsQTTiXQzZa0E3sRFj5kg95PFamXiK_e14EjTGgqYqB0J4YYdDecYS4NUlG6j7D-s6F-WfxIjnImbNssOObVnU3SUNgsBbzWA2lW5sgjl2q1JSP-s61TTlCORLhxKjR1J7-_5g8D_FK-HsxlWrNqNoxlWSK0ps8vzC5kFtitGfgrpWrQdGOWbg0QsOAEv/s728-rw-e365/Uber.png",
    titulo: "Dutch Regulator Fines Uber €290 Million for GDPR Violations in Data Transfers to U.S.",
    dataPublicacao: new Date(),
    tags: ["GDPR", "Data Protection"],
    resumo:
      "The Dutch Data Protection Authority (AP) has fined Uber €290 million for violating the General Data Protection Regulation (GDPR) in its data transfers to the U.S. The regulator found that the ride-hailing company failed to protect the personal data of its drivers and passengers.",
    autor: "Jane Doe",
    paragrafos: [
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec elit tincidunt interdum. Sed at turpis nec nunc ultricies mattis",
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec purus nec elit tincidunt interdum. Sed at turpis nec nunc ultricies mattis"
    ]  
  },
];
  
export function getNoticiaBySlug(slug: string): Noticia | undefined {
  return noticias.find((noticia) => noticia.slug === slug);
}

export function getNoticiasPreview(): NoticiaPreview[] {
  return noticias.map((noticia) => ({
    slug: noticia.slug,
    urlCapa: noticia.urlCapa,
    titulo: noticia.titulo,
    dataPublicacao: noticia.dataPublicacao,
    tags: noticia.tags,
    resumo: noticia.resumo,
  }));
}

export function getNoticiasTrending(): NoticiaTrending[] {
  return noticias.map((noticia) => ({
    slug: noticia.slug,
    urlCapa: noticia.urlCapa,
    titulo: noticia.titulo,
  }));
}

export function getPopularResources(): Resource[] {
  return [
    {
      titulo: `2024's Must-Have Guide to Continuous Pentesting and Breach Prevention`,
      url: "https://thehackernews.uk/breachlock-appsec-2024",
      urlCapa: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjSsemQgdSQ5BRgV2-wOD8IhUEikfBvf9pnFZjMWXL8iwm8k4NShIi4gC8Ahc4QEs-su4bax-YJW-3cUQnZj6YEwcTv6QQxDliEb8XJWA24ZaFFh6fNV30JYQxeBIU6oXg9S7C9LOjDw2iM3Et6zVKOVxU5p7elyZmjpm7C9QxwXnp0zzaD3XWPveIk-bZW/s72-rw-e365/appsec.png",
    },
    {
      urlCapa: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhGrnPvz8ME-gEt4Oqh6f4QE2wKLf9G1tW7u4c4bwCy_oeWe4SuD6DgKs4YJLME3AlyWIqGYXfaegH6M1fEQYa_PEij7ztKAZSr1b0D6mhQXKU_ZVOOHh0HDhExU0QE_M-dq8DMDVQ0tDcxIjXWppVw-sW4ZVRjz9smV-S3-sW8WBrnxRIgwHlFmLZrcJQM/s72-rw-e365/bot.png",
      titulo: `Top 9 Chatbots Ranked: Which One Leaves Your Business Most Vulnerable?`,
      url: "https://www.reflectiz.com/learning-hub/chatbots-risk-exposure/",
    }
  ]
}
